### PR TITLE
SCAL-130265 Remember the dark mode setting in Dev docs

### PR DESCRIPTION
**Pull request by adityamittal3107**

### CODE REVIEW

**Review by ashubham — APPROVED** [review]
Would be good if you could also add a test

**Comment by ashubham** [comment]
Also seems the deployment to vercel failed, can you try to run the build locally ?

image

Can follow the advice here https://github.com/gatsbyjs/gatsby/issues/14480

**Comment by demon12321** [comment]
> Also seems the deployment to vercel failed, can you try to run the build locally ?
> 
> image
> 
> Can follow the advice here [gatsbyjs/gatsby#14480](https://github.com/gatsbyjs/gatsby/issues/14480)

**Comment by demon12321** [comment]
I have built it locally, it was working fine there.

**Pull request merged**
